# Generated by Django 5.2.9 on 2025-12-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL용 영문 식별자 (예: humanity_talk)', null=True),
        ),
    ]
