# Generated by Django 5.2.9 on 2025-12-19 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='좋아요 누른 시간')),
            ],
            options={
                'verbose_name': '게시글 좋아요',
                'verbose_name_plural': '게시글 좋아요 목록',
                'db_table': 'community_post_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='scrap',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='scrap',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_scrap'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(help_text='좋아요 대상 게시글', on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='community.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(help_text='좋아요를 누른 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, help_text='좋아요한 사용자', related_name='liked_posts', through='community.PostLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postlike',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_like'),
        ),
    ]
