# Generated by Django 5.2.9 on 2025-12-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_board_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='slug',
            field=models.SlugField(help_text='URL용 영문 식별자 (예: humanity_talk)', unique=True),
        ),
    ]
