# Generated by Django 5.2.9 on 2025-12-19 18:08

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmooc_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('content_key', models.CharField(blank=True, max_length=500, null=True)),
                ('professor', models.CharField(blank=True, max_length=500, null=True)),
                ('org_name', models.CharField(blank=True, max_length=100, null=True)),
                ('classfy_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_classfy_name', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('course_image', models.URLField(blank=True, max_length=500, null=True)),
                ('enrollment_start', models.DateField(blank=True, null=True)),
                ('enrollment_end', models.DateField(blank=True, null=True)),
                ('study_start', models.DateField(blank=True, null=True)),
                ('study_end', models.DateField(blank=True, null=True)),
                ('week', models.FloatField(blank=True, null=True)),
                ('course_playtime', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='평점 (예: 1~5)')),
                ('review_text', models.TextField(help_text='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='리뷰 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='리뷰 수정 시각')),
                ('course', models.ForeignKey(help_text='리뷰 대상 강좌', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(help_text='리뷰 작성자', on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '강좌 리뷰',
                'verbose_name_plural': '강좌 리뷰 목록',
                'db_table': 'course_review',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='uq_course_review_user_course')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '수강중'), ('completed', '수강완료'), ('dropped', '수강취소')], default='enrolled', help_text='수강 상태 (enrolled/completed/dropped)', max_length=20)),
                ('progress_rate', models.DecimalField(decimal_places=2, default=0, help_text='진도율(%) - 0~100 범위', max_digits=5)),
                ('last_studied_at', models.DateTimeField(blank=True, help_text='마지막 학습 시점', null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, help_text='수강 신청 시점(외부 이벤트 시각 보존용)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드 수정 시각')),
                ('course', models.ForeignKey(help_text='수강 강좌', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(help_text='수강 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '수강',
                'verbose_name_plural': '수강 목록',
                'db_table': 'enrollment',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='uq_enrollment_user_course')],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='찜한 시각')),
                ('course', models.ForeignKey(help_text='찜된 강좌', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='courses.course')),
                ('user', models.ForeignKey(help_text='찜한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜 목록',
                'db_table': 'wishlist',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='uq_wishlist_user_course')],
            },
        ),
    ]
